### ISSUE TITLE
Test API Controller is created when updating the package

### ISSUE THREAD

**Issue by tomten** [degdigital/DEG.Shared.SC.EnableWebApi#2]
A new Test API Controller is created when updating the package. This isn't really needed  and just requires manual removal.

When installing the package for the first time, however, this is nice.

**Comment by PatrickDelancy** [comment]
I agree that it is helpful to have the controller there on the first install, but I don't think it is possible to skip it on an update.

When you "update" a nuget package, it actually just removes it and re-installs it, which will re-add the test controller.

If I get enough complaints, I'll just remove the test controller entirely, but for now I'm not sure that I can do anything.

**Comment by tomten** [comment]
Well, couldn't you just skip the test Controller if there already are any Web API Controllers in the project? :)

**Comment by PatrickDelancy** [comment]
I'll have to research that a little bit more. I'm sure this could be done with a custom powershell script to search the project for existing api controllers, but then I question the value we get out of that much effort.

**Comment by tomten** [comment]
Why, the educational value for you alone would be tremendous! :)

If a rainy day should occur in the near future, I may look into it. Thanks.
